books/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'<book_id>/', views.detail, name='detail')
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'books/', include('books.urls')),
]

books/models.py
from django.db import models

# Create your models here.

#creates a table in db.sqlite
class Book(models.Model):
    
    #returns the database results
    def __str__(self):
        return self.name + " - " + self.author
    
    name = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    price = models.CharField(max_length=50)
    type = models.CharField(max_length=50)
    
    
#syntax for creating a table 
# class table_name(models.Model):
#     attributes come here

books/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Book
from django.template import loader
from django.shortcuts import render
from django.http import Http404

# Create your views here.

def index(request):
    #To get all books in the db
    all_books = Book.objects.all()
    # html = ''
    # for book in all_books:
    #     url = '/books/' + str(book.id) + '/'
    #     html+= '<a href="'+ url +'">' + str(book.name) + '</a><br>'
    # # return HttpResponse("<h>This is the books homepage</h>")
    # return HttpResponse(html)
    # template = loader.get_template('books/index.html')
    context={
        'all_books':all_books
    }
    # return HttpResponse(template.render(context, request))
    return render(request, 'books/index.html', context)
    
    
def detail(request, book_id):
    try:
        book = Book.objects.get(id = book_id)
    except Book.DoesNotExist:
        raise Http404("This book does not exist")
    # return HttpResponse("<h2>Details for Book ID: " + str(book_id) + "</h2>")
    return render(request, 'books/detail.html', {'book':book})

books/templates/books/detail.html
{{book}}

books/templates/books/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='../../static/books/style.css'>
    <link rel="stylesheet" type="txt/css" href="../../bootstrap-4.3.1-dist/css/bootstrap.css">
    <!-- <link rel="stylesheet" type="text/js" href="../../bootstrap-4.3.1-dist/js/bootstrap.min.js"> -->
    <!-- <script src='main.js'>
    </script> -->
</head>

<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'books:index' %}">The BookStore</a>
        </div>
    </nav>
    <ul>{%for book in all_books%}
        <li>
            <!-- <a href=" /books/{{book.id}}/ ">{{book.name}}</a> -->
            <a href="{% url 'books:detail' book.id %} ">{{book.name}}</a>
        </li>{%endfor%}</ul>

</body>

</html>